name: The Digital Experience
favicon: null
layout_spectrum: 0.72772
typography_spectrum: 0.73165
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#212832'
    - '#eeeeee'
    - '#00adb4'
    - '#115c67'
    - '#5bb8ba'
  brandStrength: 1
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
