name: The Digital Experience
favicon: null
layout_spectrum: 0.72772
typography_spectrum: 0.73165
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f33535'
    - '#d8e9f0'
    - '#28252c'
    - '#32425b'
    - '#f6c2c3'
  brandStrength: 1
  lightness: 0.25
  saturation: 0
  rhythmicContrast: 1
purpose: []
