name: The Digital Experience
favicon: null
layout_spectrum: 0.22131
typography_spectrum: 0.73165
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-125626-11
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f05052'
    - '#e1eec3'
    - '#f8d320'
    - '#f5903c'
    - '#7b6212'
  brandStrength: 0
  lightness: 0.3125
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
