name: The Digital Experience
favicon: null
layout_spectrum: 0.72772
typography_spectrum: 0.73165
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0097fe'
    - '#ff5700'
    - '#aaaaaa'
    - '#3785c5'
    - '#b06c4d'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
