name: The Digital Experience
favicon: null
layout_spectrum: 0.34545
typography_spectrum: 0.57363
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a7a9ac'
    - '#770606'
    - '#ffffff'
    - '#00ffff'
    - '#0000ff'
  brandStrength: 0.8125
  lightness: 0.1875
  saturation: 0.375
  rhythmicContrast: 0.6243456860538572
purpose: []
