name: The Digital Experience
favicon: null
layout_spectrum: 0.52866
typography_spectrum: 0.14007
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-125626-11
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b5a397'
    - '#30231d'
    - '#f6f1ed'
    - '#6a5750'
    - '#7f756f'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
