name: The Digital Experience
favicon: null
layout_spectrum: 0.49167
typography_spectrum: 0.2576
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#012444'
    - '#fcfcfc'
    - '#a5a7b4'
    - '#f73e00'
    - '#ff7f24'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
