name: The Digital Experience
favicon: null
layout_spectrum: 0.60133
typography_spectrum: 0.73165
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#adc1d6'
    - '#f2bc00'
    - '#ff542e'
    - '#fff0ba'
    - '#ff907c'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
