name: The Digital Experience
favicon: null
layout_spectrum: 0.50637
typography_spectrum: 0.73165
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#222222'
    - '#de4564'
    - '#2179a9'
    - '#f2733c'
    - '#8b8b8b'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
