name: The Digital Experience
favicon: null
layout_spectrum: 0.56513
typography_spectrum: 0.73165
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-125626-11
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6f5441'
    - '#ddad58'
    - '#bb405f'
    - '#f5cfd8'
  brandStrength: 1
  lightness: 0.5625
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
