name: The Digital Experience
favicon: null
layout_spectrum: 0.49702
typography_spectrum: 0.57363
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#004c66'
    - '#d3edfe'
    - '#3791d0'
    - '#69451f'
    - '#a8792a'
  brandStrength: 0.125
  lightness: 0.875
  saturation: 0.375
  rhythmicContrast: 0
purpose: []
