name: The Digital Experience
favicon: null
layout_spectrum: 0.78844
typography_spectrum: 0.2576
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#646464'
    - '#be242d'
    - '#a9a9a9'
    - '#060000'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
