name: The Digital Experience
favicon: null
layout_spectrum: 0.63463
typography_spectrum: 0.73165
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fe5335'
    - '#dee0d3'
    - '#3f92a4'
    - '#353a40'
    - '#de7d6c'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
