name: The Digital Experience
favicon: null
layout_spectrum: 0.22131
typography_spectrum: 0.73165
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-125626-11
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#28353b'
    - '#99b899'
    - '#feceaa'
    - '#f4837d'
    - '#ea495f'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
