favicon: null
name: The Digital Experience
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5
  brandStrength: 0.25
  rhythmicContrast: 0.25
  brandColors:
    - '#ffffff'
    - '#3b3a36'
    - '#b3c2bf'
    - '#000000'
    - '#898c85'
  lightness: 0.375
typography_spectrum: 0.14007
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0
analytics:
  twitter: null
  google: UA-125626-11
  facebook: null
