name: The Digital Experience
favicon: null
layout_spectrum: 0.38258
typography_spectrum: 0.73165
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefff9'
    - '#c7632f'
    - '#d0d1cb'
    - '#5b3824'
    - '#6e6f69'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
